### ISSUE TITLE
Something wrong with my config file?

### ISSUE THREAD

**Issue by jessetandor** [tchiotludo/kafkahq#141] opened 2019-11-07 13:19 UTC
I'm trying to run with this config file - its the bare minimum from what i can see. The broker has sasl configured and its running on a remote machine ( URL specified in bootstrap ). Did I miss anything?

```
kafkahq:
  connections:
    Dev-multi-kafka-test:
      properties:
        bootstrap.servers: "kafka-mdb1.dev-tll.workshop.works:9092"
            security.protocol: SASL_SSL
            sasl.mechanism: SCRAM-SHA-256
            sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="admin_pass" password="123";
            ssl.truststore.location: /app/truststore.jks
            ssl.truststore.password: password
            ssl.keystore.location: /app/keystore.jks
            ssl.keystore.password: password
            ssl.key.password: password
```

**Comment by tchiotludo** [comment] 2019-11-07 13:37
Hard to say like that.

What is your env (runtime docker or jar with java version) ? 
What does the log output ? 
What is the error on brower ? 
... 

The only things is see is uppercase on `Dev-multi-kafka-test` that if not tested by myself, always lowercase.

**Comment by jessetandor** [comment] 2019-11-07 14:07
I'm running docker locally on my machine. I just get output from the command 
`docker run -d  -p 8080:8080 -v /Users/jesse/Desktop/application.yml:/app/application.yml tchiotludo/kafkahq` which is `89e321e7e30d37c0311235ec1a9a64a361a74e51f86b7b8e1a54036ea1fe21cc`

And checking the logs from docker - `docker logs 89e321e7e30d37c0311235ec1a9a64a361a74e51f86b7b8e1a54036ea1fe21cc`

```
2019-11-07 14:06:34,952 ERROR main       i.m.runtime.Micronaut      Error starting Micronaut server: while parsing a block mapping
 in 'reader', line 5, column 9:
            bootstrap.servers: "kafka-mdb1.d ...
            ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 6, column 11:
              security.protocol: SASL_SSL
              ^

org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 5, column 9:
            bootstrap.servers: "kafka-mdb1.d ...
            ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 6, column 11:
              security.protocol: SASL_SSL
```

It looks like my syntax is incorrect somehow...

**Comment by tchiotludo** [comment] 2019-11-07 14:09
yes seems to be in the yaml matrix, maybe to space failed : try here your yaml : http://www.yamllint.com/

**Comment by jessetandor** [comment] 2019-11-07 14:23
bootstrap.servers: "kafka-mdb1.dev-tll.workshop.works:9092"
            security.protocol: SASL_SSL

Was the problem. It should be 

        bootstrap.servers: "kafka-mdb1.dev-tll.workshop.works:9092"
        security.protocol: SASL_SSL

**Comment by tchiotludo** [comment] 2019-11-07 14:26
:+1: closing if it work :)

**Closed by tchiotludo** 2019-11-07 14:26 UTC
Labels: question

**Comment by jessetandor** [comment] 2019-11-14 08:20
I still can't connect to the broker though :

{"message":"Internal Server Error: Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly","logref":{"present":false},"path":{"present":false}}

The config file is correct - no errors:

_---
kafkahq:
  connections:
    dev:
      properties:
        bootstrap.servers: "kafka-mdb1.dev-tll.workshop.works:9092"
        sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"cluster_admin\" password=\"123\";"
        sasl.mechanism: SCRAM-SHA-256
        security.protocol: SASL_SSL_

kafka-mdb1.dev-tll.workshop.works is the machine hostname - I've also tried to use the general cluster name from consul itself ( kafka-microservices-db.service.consul:9092 ). And then also the IP address of the kafka-mdb1 machine... None have connected.

Im mainly using the java method - 'java -Dmicronaut.config.files=application.yml -jar kafkahq.jar'. Both files in the same directory.

Anything else i can try?

**Comment by tchiotludo** [comment] 2019-11-14 08:25
mostly must be a indentation problem ! 
This error was throw by KafkaHQ to expose that the file is incorrect.

Can you attach the raw files please ? or here is the correct version : 

```yaml
kafkahq:
  connections:
    dev:
      properties:
        bootstrap.servers: "kafka-mdb1.dev-tll.workshop.works:9092"
        sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username="cluster_admin" password="123";"
        sasl.mechanism: SCRAM-SHA-256
        security.protocol: SASL_SSL
```

**Comment by jessetandor** [comment] 2019-11-14 08:36
That fails...Tit complains that the syntax is incorrect without \ for username and password.

kafkahq:
  connections:
    dev:
      properties:
        bootstrap.servers: "kafka-microservices-db.service.consul:9092"
        sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"cluster_admin\" password=\"123\";"
        sasl.mechanism: SCRAM-SHA-256
        security.protocol: SASL_SSLL

**Comment by tchiotludo** [comment] 2019-11-14 08:41
ok I see the " failed.
try with this : 

```yaml 
kafkahq:
  connections:
    dev:
      properties:
        bootstrap.servers: "kafka-mdb1.dev-tll.workshop.works:9092"
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="cluster_admin" password="123";
        sasl.mechanism: SCRAM-SHA-256
        security.protocol: SASL_SSL
```

**Comment by jessetandor** [comment] 2019-11-14 10:35
Syntax is working but still the same error. 

- If three machines are in the cluster - do all three need to be specified?
- how does the jar handle consul URL's?

Trying from Docker also gives me afew problems - the container is up. No config errors from command

docker run -d \
>     -p 2000:2000 \
>     -v /Users/jesse/Desktop/application.yml:/app/application.yml \
>     tchiotludo/kafkahq
b69c8acea74b6c76ce7c422aa6dc71dadb25f1c3760933fc1bdd50f29a704fd4

From docker logs (docker logs b69c8acea74b6c76ce7c422aa6dc71dadb25f1c3760933fc1bdd50f29a704fd4) :
i.m.runtime.Micronaut      Startup completed in 3380ms. Server Running: http://b69c8acea74b:8080

That URL isn't resolvable.. unsure if that's an issue on my side (DNS maybe). Also why is it using 8080 in response..shouldn't it be 2000?

**Comment by tchiotludo** [comment] 2019-11-14 10:38
- Only 1 machine is mandatory, give more is better but unneeded 
- Nothing is done to handle consul right now, you must specify direct connection with the broker.

for the docker run, it's a normal behavior, you must use a  `-p 2000:8080`, -p mean localPort:containerPort and you shoud access to webserver with localhost:2000 in your case

**Comment by jessetandor** [comment] 2019-11-14 13:49
Seems a connection is made but the broker somehow isn't detected. We only have sasl configured which I've already specified in the config:

```
2019-11-14 13:34:31,936 WARN  inclient-1 o.a.k.c.NetworkClient      [AdminClient clientId=adminclient-1] Connection to node -1 (kafka-mdb1.dev-tll.workshop.works/192.168.xx.xxx:9092) could not be established. Broker may not be available.
```
It correctly picks up the IP of the node though...

**Comment by tchiotludo** [comment] 2019-11-14 13:55
Ok kafkahq is working, but the connection to kafka is down. 
You can go into the container with `docker exec -it container-id bash` and try connectivity with telnet or nc.
Seems that your container can't reach your ip

**Comment by jessetandor** [comment] 2019-11-15 11:38
Yes, IP was incorrect. It's talking to the machine now but auth is not working as it should.

Is there a way to get more info/debug/check logs for the java version. From the docker version, it says what the problem might be ( Older brokers, Firewall blocking Kafka TLS, random nework issues).

**Comment by tchiotludo** [comment] 2019-11-15 11:56
With kafkaHQ, you can raise log level with that : 

Go on http://localhost:8080/loggers to list logger and you can change specific logger with that curl 
```
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:8080/loggers/org.kafkahq
```
Works with jar & docker

**Comment by jessetandor** [comment] 2019-11-15 13:18
For ERROR - it seems nothing from my config is being read??
```
{"configuredLevel":"NOT_SPECIFIED","effectiveLevel":"ERROR"},"org.kafkahq.controllers.ErrorController":{"configuredLevel":"NOT_SPECIFIED","effectiveLevel":"ERROR"},"org.kafkahq.log":{"configuredLevel":"NOT_SPECIFIED","effectiveLevel":"ERROR"},"org.kafkahq.log.access":{"configuredLevel":"NOT_SPECIFIED","effectiveLevel":"ERROR"},"org.kafkahq.modules":{"configuredLevel":"NOT_SPECIFIED","effectiveLevel":"ERROR"},"org.kafkahq.modules.KafkaModule":{"configuredLevel":"NOT_SPECIFIED","effectiveLevel":"ERROR"},"org.kafkahq.modules.RequestHelper":{"configuredLevel":"NOT_SPECIFIED","effectiveLevel":"ERROR"},"org.kafkahq.repositories":{"configuredLevel":"NOT_SPECIFIED","effectiveLevel":"ERROR"},"org.kafkahq.repositories.RecordRepository":{"configuredLevel":"NOT_SPECIFIED","effectiveLevel":"ERROR"},"org.kafkahq.utils":{"configuredLevel":"NOT_SPECIFIED","effectiveLevel":"ERROR"},"org.kafkahq.utils.Lock":
```
Full file below
[full.txt](https://github.com/tchiotludo/kafkahq/files/3851614/full.txt)

**Comment by tchiotludo** [comment] 2019-11-21 20:18
Sorry, missed this one. 
The page don't display log, it only list loggers & log level for each one. 
And the POST version allow to change to more verbose log. 

```bash
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:8080/loggers/org.apache.kafka.clients
```
I think this is the right command to understand kafka connectivity issue

**Comment by jessetandor** [comment] 2019-11-25 11:17
Caught this from TRACE logs :
SSLHandshake handshakeUnwrap: handshakeStatus NEED_UNWRAP status BUFFER_UNDERFLOW

And this from DEBUG:
Failed to send SSL Close message
java.io.IOException: Unexpected status returned by SSLEngine.wrap, expected CLOSED, received OK. Will not send close message to peer.

...

**Comment by tchiotludo** [comment] 2019-11-25 11:43
The problem is that the option is changing how the cluster is defined and there is many case. 
Since it was a kafka configuration, I hope that the kafka docs will handle that case for me.

**Comment by CiprianAmza** [comment] 2023-04-11 13:25
Hello, I wonder what I'm doing wrong. 
I have this docker configuration:

version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  akhq:
    image: tchiotludo/akhq:latest
    ports:
      - "8070:8070"
    environment:
      - AKHQ_OPTS=-Dakka.remote.artery.canonical.port=2551 -Dakka.management.http.port=8559
      - SPRING_PROFILES_ACTIVE=prod
      - AKHQ_CLUSTER_1_BOOTSTRAP_SERVERS=football-manager-simulator-kafka-1:9092
    command: sh -c "cp /app/application.yml.example /app/application.yml && ./akhq"
    volumes:
      - ./src/main/resources/application.yml:/app/application.yml.example
      - ./src/main/resources:/app/config


I get no error, it looks like kafka is connecting, also micronaut gives me a warning, but no error. However, I can't access the interface at localhost:8070. Is there anything else I should do in order to be able to access the interface?
